repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    # Identify invalid files
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    # git checks
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-case-conflict
    # Python checks
    -   id: check-docstring-first
    -   id: debug-statements
    # General checks
    -   id: mixed-line-ending
        exclude: ".fits"
    -   id: trailing-whitespace
        exclude: ".fits"
    -   id: end-of-file-fixer

# Ruff - Modern Python linter and formatter (replaces isort, black, flake8, pyupgrade)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    # Run the linter
    -   id: ruff
        args: [--fix]
    # Run the formatter
    -   id: ruff-format
