;restore,'slit_func.sav'
;restore,'bkl.sav'
;osample=10L
;ncol=205L
;nrow=11L
;ny=121L
restore,'slit_func1.sav'
osample=long(osamp)
ncol=long(nc)
nrow=long(nysf)
ny=(nrow+1L)*osample+1L
sf=double(sf)
ycen=double(ycen[ib:ie])-yc[ib:ie]
msk=replicate(1B,ncol,nrow)
openw,1,'slit_func1.dat'
writeu,1,osample,ncol,nrow,ny
writeu,1,msk
writeu,1,sf
writeu,1,ycen
;writeu,1,bkl
close,1
end
